{% set name = "jarowinkler" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jarowinkler-{{ version }}.tar.gz
  sha256: 206364a885ce296f7f79c669734317f2741f6bbd964907e49e3b9ea0e9de5029

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - pip
    - python
    - scikit-build
    - wheel
    - setuptools
    - rapidfuzz_capi
  run:
    - python

test:
  imports:
    - jarowinkler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxbachmann/JaroWinkler
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: library for fast approximate string matching using Jaro and Jaro-Winkler similarity
  dev_url: https://github.com/maxbachmann/JaroWinkler

extra:
  recipe-maintainers:
    - maxbachmann
