{% set name = "jarowinkler" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jarowinkler-{{ version }}.tar.gz
  sha256: af28ea284cfbd1b21b29ff94b759f20e94e4f7c06f424b0b4702e701c2a21668

build:
  # fail to find the correct head path for Python. This will hopefully improve in scikit-build at some point
  skip: true  # [python_impl == 'pypy' and (linux and (aarch64 or ppc64le))]
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - pip
    - python
    - scikit-build
    - wheel
    - setuptools
    - rapidfuzz_capi
  run:
    - python

test:
  imports:
    - jarowinkler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxbachmann/JaroWinkler
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: library for fast approximate string matching using Jaro and Jaro-Winkler similarity
  dev_url: https://github.com/maxbachmann/JaroWinkler

extra:
  recipe-maintainers:
    - maxbachmann
