{% set name = "jarowinkler" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jarowinkler-{{ version }}.tar.gz
  sha256: 7118976b9c1dca4ad77c97a0595d3917cead5f9b2856b14948a3bcf5f2438c44

build:
  number: 0
  script:
#     - export CMAKE_OSX_ARCHITECTURES="arm64"
#     - # workaround for https://github.com/scikit-build/scikit-build/issues/589
#     - rm -rf $PREFIX/lib/libpython$PY_VER.dylib
#     - ln -sf $PREFIX/lib/libc++.dylib $PREFIX/lib/libpython$PY_VER.dylib
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - scikit-build                           # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - pip
    - python
    - scikit-build
    - wheel
    - setuptools
    - rapidfuzz_capi
  run:
    - python

test:
  imports:
    - jarowinkler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxbachmann/JaroWinkler
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: library for fast approximate string matching using Jaro and Jaro-Winkler similarity
  dev_url: https://github.com/maxbachmann/JaroWinkler

extra:
  recipe-maintainers:
    - maxbachmann
