{% set name = "jarowinkler" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jarowinkler-{{ version }}.tar.gz
  sha256: 7118976b9c1dca4ad77c97a0595d3917cead5f9b2856b14948a3bcf5f2438c44
  patches:
    - patches/test.patch

build:
  # crashes on import, since something goes wrong cross compiling
  # This should be related to https://github.com/scikit-build/scikit-build/issues/589 but I could not get a workaround working
  # at least partly because I do not have a mac for testing
  skip: true  # [osx and arm64]
  # for some completely unknown reason these crash on import in the CI.
  # It is unclear to me how segmentation faults in the conda forge build can be debugged
  skip: true  # [linux and py==37 and (aarch64 or ppc64le)]
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - pip
    - python
    - scikit-build
    - wheel
    - setuptools
    - rapidfuzz_capi
  run:
    - python

test:
  imports:
    - jarowinkler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxbachmann/JaroWinkler
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: library for fast approximate string matching using Jaro and Jaro-Winkler similarity
  dev_url: https://github.com/maxbachmann/JaroWinkler

extra:
  recipe-maintainers:
    - maxbachmann
