{% set name = "jarowinkler" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jarowinkler-{{ version }}.tar.gz
  sha256: 7640c79f8d2d5e9eed6691cb49e3018a23b2319daad9a2178df253368b5432b7

build:
  noarch: python
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - python >=3.8
  host:
    - python {{ python_min }}
    - pip
    - rapidfuzz >=3.5.2
  run:
    - python >={{ python_min }}
    - rapidfuzz >=3.5.2

test:
  imports:
    - jarowinkler
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/maxbachmann/JaroWinkler
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: library for fast approximate string matching using Jaro and Jaro-Winkler similarity
  dev_url: https://github.com/maxbachmann/JaroWinkler

extra:
  recipe-maintainers:
    - maxbachmann
